import Link from "next/link";
import { requireServerSession } from "@/src/auth/server";
import { participantForUser } from "@/src/study/context";
import { participantSurveys } from "@/src/study/surveys";

export default async function SurveysPage() {
  const session = await requireServerSession(); const participant = await participantForUser(session.userId); const surveys = participant ? await participantSurveys(participant.id) : []; const now = new Date();
  return <main id="main-content" className="app-content"><nav className="breadcrumbs"><Link href="/participant">Today</Link><span>/</span><span>Research questions</span></nav><div className="app-title"><div><p className="eyebrow">Optional and low burden</p><h1>Research questions</h1><p>You can save, snooze, skip or dismiss. These schedules are independent of how often you use the programme.</p></div></div><div className="notice"><strong>These are original pilot questions, not validated clinical measures.</strong> No licensed questionnaire wording is included without approval.</div><div className="survey-list">{surveys.length === 0 && <p>No surveys have been scheduled.</p>}{surveys.map((survey) => { const future = survey.windowOpensAt > now; const closed = survey.windowClosesAt < now; const snoozed = survey.status === "snoozed" && survey.snoozedUntil && survey.snoozedUntil > now; return <article key={survey.id}><div><span className={`tag ${survey.status === "completed" ? "tag--open" : ""}`}>{survey.status.replaceAll("_", " ")}</span><h2>{survey.name}</h2><p>{survey.purpose}</p><p className="microcopy">Version {survey.version} · Window {survey.windowOpensAt.toLocaleDateString("en-GB")} to {survey.windowClosesAt.toLocaleDateString("en-GB")}</p></div>{survey.status === "completed" ? <span>Completed</span> : future ? <span>Opens later</span> : closed ? <span>Window closed</span> : snoozed ? <span>Snoozed</span> : ["skipped", "dismissed", "expired"].includes(survey.status) ? <span>Closed</span> : <Link className="button button--small" href={`/participant/surveys/${survey.id}`}>Open survey</Link>}</article>; })}</div></main>;
}
