"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

function csrfToken() { return decodeURIComponent(document.cookie.split("; ").find((part) => part.startsWith("mpft_csrf="))?.split("=").slice(1).join("=") ?? ""); }
export function GamblingSimulationPanel() {
  const router = useRouter(); const [message, setMessage] = useState(""); const [result, setResult] = useState<Record<string, unknown> | null>(null); const [status, setStatus] = useState(""); const [busy, setBusy] = useState(false);
  async function simulate() { setBusy(true); const response = await fetch("/api/staff/gambling/simulate", { method: "POST", headers: { "content-type": "application/json", "x-csrf-token": csrfToken() }, body: JSON.stringify({ message }) }); const body = await response.json().catch(() => ({})); setBusy(false); setResult(body); }
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); const response = await fetch("/api/staff/gambling/check-in", { method: "POST", headers: { "content-type": "application/json", "x-csrf-token": csrfToken() }, body: JSON.stringify({ date: form.get("date"), gamblingOccurred: form.get("gamblingOccurred") === "yes", urge: Number(form.get("urge")), episodes: Number(form.get("episodes")), moneyStakedPence: Math.round(Number(form.get("moneyStakedPounds")) * 100), moneyLostPence: Math.round(Number(form.get("moneyLostPounds")) * 100), currency: "GBP", chasing: form.get("chasing") === "yes", distress: Number(form.get("distress")), protectiveActions: form.getAll("protectiveActions") }) }); const body = await response.json().catch(() => ({})); setBusy(false); setStatus(String(body.message ?? "Record could not be saved.")); if (response.ok) router.refresh(); }
  const actions = Array.isArray(result?.actions) ? result.actions as Array<{ code: string; title: string; detail: string }> : [];
  return <div className="gambling-sim-grid"><section className="staff-section"><h2>Immediate “I am about to gamble” simulation</h2><p>This deterministic path runs before any generative output. Leave the box empty for a routine urge, or enter a synthetic hazard phrase to test routing.</p><label htmlFor="gambling-message">Synthetic test phrase <span>Not stored</span></label><textarea id="gambling-message" rows={3} maxLength={500} value={message} onChange={(event) => setMessage(event.target.value)} placeholder="For example: I am about to gamble" /><button className="button" type="button" onClick={() => void simulate()} disabled={busy}>Run protective route</button>{result && <div className={result.kind === "boundary" ? "notice notice--warning" : "structured-actions"} role="status">{result.kind === "boundary" ? <><h3>Safety boundary</h3><p>{String(result.message)}</p><a href="/help">Open support routes</a></> : actions.map((action) => <article key={action.code}><h3>{action.title}</h3><p>{action.detail}</p></article>)}</div>}</section><section className="staff-section"><h2>Add synthetic gambling check-in</h2><form className="simulation-form" onSubmit={save}><label>Date<input name="date" type="date" required /></label><label>Urge, 0–10<input name="urge" type="number" min="0" max="10" required /></label><label>Distress, 0–10<input name="distress" type="number" min="0" max="10" required /></label><label>Episodes<input name="episodes" type="number" min="0" max="1000" required /></label><label>Money staked, GBP<input name="moneyStakedPounds" type="number" min="0" max="1000000" step="0.01" required /></label><label>Money lost, GBP<input name="moneyLostPounds" type="number" min="0" max="1000000" step="0.01" required /></label><fieldset className="question"><legend>Gambling occurred?</legend><label><input type="radio" name="gamblingOccurred" value="yes" required />Yes</label><label><input type="radio" name="gamblingOccurred" value="no" />No</label></fieldset><fieldset className="question"><legend>Chasing losses?</legend><label><input type="radio" name="chasing" value="yes" required />Yes</label><label><input type="radio" name="chasing" value="no" />No</label></fieldset><fieldset className="question"><legend>Protective actions</legend><div className="check-list">{[["bank-block-active","Bank block active"],["self-exclusion-active","Self-exclusion active"],["money-access-limited","Access to money limited"],["trusted-person","Trusted person contacted"],["specialist-support","Specialist support contacted"],["none","None recorded"]].map(([value,label]) => <label key={value}><input type="checkbox" name="protectiveActions" value={value} />{label}</label>)}</div></fieldset><button className="button" disabled={busy}>Save synthetic record</button>{status && <p role="status">{status}</p>}</form></section></div>;
}
