import Link from "next/link";
import { requireServerPermission } from "@/src/auth/server";
import { gamblingSimulationData } from "@/src/gambling/simulation";
import { releaseGate } from "@/src/governance/release-gates";
import { GamblingSimulationPanel } from "@/src/ui/staff/GamblingSimulationPanel";

export default async function StaffGamblingPage() {
  await requireServerPermission("research:deidentified"); const [data, gate] = await Promise.all([gamblingSimulationData(), releaseGate("gambling_participant", "GAMBLE-STAFF-SIMULATION")]); const baseline = (data?.baseline?.gambling ?? {}) as Record<string, unknown>;
  return <main id="main-content" className="app-content"><nav className="breadcrumbs"><Link href="/staff">Overview</Link><span>/</span><span>Gambling staff simulation</span></nav><div className="app-title"><div><p className="eyebrow">Separate protocol and release</p><h1>Gambling staff simulation</h1><p>Synthetic data capture and deterministic safety testing only.</p></div><span className="tag tag--warning">Participant access closed</span></div><div className="notice"><strong>Live gambling coaching is fail-closed.</strong> {gate.reasons.join(", ").replaceAll("_", " ")}. No participant-facing gambling route exists, and automated tests cannot authorise one.</div><div className="staff-metrics"><article><span>Simulation participant</span><strong>{data?.participantCode ?? "—"}</strong><small>synthetic staff record</small></article><article><span>Baseline gambling days</span><strong>{String(baseline.gamblingDaysPast30 ?? "unknown")}</strong><small>past 30 days, custom field</small></article><article><span>Check-ins</span><strong>{data?.checkins.length ?? 0}</strong><small>immutable source records</small></article><article><span>Follow-ups</span><strong>{data?.outcomes.length ?? 0}</strong><small>custom synthetic fields; no validated scale claimed</small></article></div><div className="notice"><strong>Measure wording is not approved.</strong> Screening/risk characterisation and responsive outcome measures must remain separate, and sponsor-confirmed wording, scoring and licensing are still required.</div><GamblingSimulationPanel /><section className="staff-section"><h2>Recent synthetic records</h2><div className="table-scroll staff-table"><table><thead><tr><th>Date</th><th>Occurred</th><th>Urge</th><th>Episodes</th><th>Staked/lost</th><th>Chasing</th><th>Distress</th><th>Protection</th></tr></thead><tbody>{data?.checkins.map((row) => <tr key={row.id}><td>{row.scheduledFor}</td><td>{row.gamblingOccurred ? "yes" : "no"}</td><td>{row.gamblingUrge ?? "unknown"}</td><td>{row.gamblingEpisodes ?? "unknown"}</td><td>£{((row.moneyGambledPence ?? 0) / 100).toFixed(2)} / £{((row.gamblingLossPence ?? 0) / 100).toFixed(2)} {row.currency}</td><td>{row.chasing == null ? "unknown" : row.chasing ? "yes" : "no"}</td><td>{row.distress ?? "unknown"}</td><td>{row.financialProtectionCodes?.join(", ") || "none recorded"}</td></tr>)}</tbody></table></div></section></main>;
}
