import Link from "next/link";
import { CalendarCheck, ChevronRight, CircleAlert, ClipboardList, Sparkles } from "lucide-react";
import { requireServerSession } from "@/src/auth/server";
import { participantOverview } from "@/src/study/participant";

export default async function ParticipantDashboard() {
  const session = await requireServerSession();
  const overview = await participantOverview(session.userId);
  if (!overview) return <main id="main-content" className="app-content"><div className="error-summary"><h1>No participant record</h1><p>This account has no participant record for the current study.</p></div></main>;
  const next = !overview.consent ? { href: "/participant/onboarding", title: "Review consent and complete baseline", text: "Finish the draft onboarding route before using the programme." } : !overview.plan ? { href: "/participant/plan", title: "Make your change plan", text: "Choose a goal, triggers and practical coping actions." } : { href: "/participant/check-in", title: "Complete today’s check-in", text: "A brief record of smoking, craving and confidence." };
  return <main id="main-content" className="app-content"><div className="app-title"><div><p className="eyebrow">Participant {overview.participant.participantCode}</p><h1>Today</h1><p>Welcome back, {session.displayName}. This account contains fictional research data.</p></div><span className="tag tag--open">Synthetic participant</span></div><section className="next-action" aria-labelledby="next-action-title"><div className="next-action__icon"><Sparkles aria-hidden="true" /></div><div><p className="eyebrow">Next best action</p><h2 id="next-action-title">{next.title}</h2><p>{next.text}</p><Link className="button" href={next.href}>Continue <ChevronRight aria-hidden="true" size={18} /></Link></div></section><div className="dashboard-grid"><Link className="dashboard-card" href="/participant/check-in"><CalendarCheck aria-hidden="true" /><span><strong>Check in</strong><small>{overview.recentCheckIn ? `Last record: ${overview.recentCheckIn.date}` : "No check-in recorded yet"}</small></span><ChevronRight aria-hidden="true" /></Link><Link className="dashboard-card" href="/participant/plan"><ClipboardList aria-hidden="true" /><span><strong>My plan</strong><small>{overview.plan ? "Review or revise your plan" : "No active plan yet"}</small></span><ChevronRight aria-hidden="true" /></Link><Link className="dashboard-card" href="/participant/surveys"><CircleAlert aria-hidden="true" /><span><strong>Research questions</strong><small>{overview.availableSurveyCount ? `${overview.availableSurveyCount} available` : "Nothing due today"}</small></span><ChevronRight aria-hidden="true" /></Link></div><aside className="not-monitored"><strong>This website is not monitored.</strong> If you need urgent help, use the <Link href="/help">help and support page</Link>. Essential coping tools work without AI.</aside></main>;
}
