import Link from "next/link";
import { requireServerPermission } from "@/src/auth/server";
import { displayCount } from "@/src/research/disclosure";
import { researchSummary } from "@/src/research/dashboard";

export default async function StaffDashboardPage() {
  await requireServerPermission("research:deidentified"); const summary = await researchSummary();
  return <main id="main-content" className="app-content"><div className="app-title"><div><p className="eyebrow">Synthetic research operations</p><h1>Study overview</h1><p>Feasibility signals with explicit denominators, missingness and release boundaries.</p></div><span className="tag tag--warning">Not authorised for live pilot</span></div><div className="notice"><strong>Small-number disclosure control is active.</strong> Non-zero cells below the configured threshold display as &lt;5. This dashboard describes synthetic records and cannot establish causation.</div><section className="staff-section"><h2>Participant flow</h2><div className="staff-metrics"><article><span>Registered</span><strong>{displayCount(summary.participants)}</strong><small>all participant records</small></article><article><span>Consented</span><strong>{displayCount(summary.consented)}</strong><small>current state</small></article><article><span>Active</span><strong>{displayCount(summary.active)}</strong><small>current state</small></article><article><span>Withdrawn</span><strong>{displayCount(summary.withdrawn)}</strong><small>audit retained</small></article></div><Link className="plain-button" href="/staff/participants">Review de-identified flow</Link></section><section className="staff-section"><h2>Completion and missingness</h2><div className="staff-metrics"><article><span>Check-ins completed</span><strong>{displayCount(summary.checkins_completed)}</strong><small>completed records only</small></article><article><span>Progress missing</span><strong>{displayCount(summary.progress_missing)}</strong><small>of {displayCount(summary.progress_total)} scheduled days</small></article><article><span>Surveys complete</span><strong>{displayCount(summary.surveys_completed)}</strong><small>of {displayCount(summary.surveys_total)} instances</small></article><article><span>Follow-ups complete</span><strong>{displayCount(summary.followups_completed)}</strong><small>of {displayCount(summary.followups_total)}; {displayCount(summary.followups_overdue)} overdue</small></article></div></section><section className="dashboard-grid"><Link className="dashboard-card" href="/staff/safety"><span><strong>Safety and quality</strong><small>{displayCount(summary.safety_open)} open of {displayCount(summary.safety_total)} recorded; not an emergency command centre</small></span></Link><Link className="dashboard-card" href="/staff/ai"><span><strong>AI reliability and cost</strong><small>{displayCount(summary.coach_fallback)} fallback · {displayCount(summary.coach_refused)} refused · ${Number(summary.cost_usd).toFixed(4)}</small></span></Link><Link className="dashboard-card" href="/staff/exports"><span><strong>Exports and report</strong><small>Versioned, de-identified and audited</small></span></Link></section></main>;
}
