"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

export function CheckInForm({ completed }: { completed: boolean }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError(""); const form = new FormData(event.currentTarget);
    const csrf = document.cookie.split("; ").find((part) => part.startsWith("mpft_csrf="))?.split("=").slice(1).join("=") ?? "";
    const response = await fetch("/api/participant/check-in", { method: "POST", headers: { "content-type": "application/json", "x-csrf-token": decodeURIComponent(csrf) }, body: JSON.stringify({ smokingStatus: form.get("smokingStatus"), cigarettes: Number(form.get("cigarettes")), craving: Number(form.get("craving")), confidence: Number(form.get("confidence")), goalAttempted: form.get("goalAttempted") === "yes", triggerCodes: form.getAll("triggerCodes").map(String), copingActionCodes: form.getAll("copingActionCodes").map(String), positiveMomentCode: form.get("positiveMomentCode") }) });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) { setError(String(data.message ?? "The check-in could not be saved.")); setBusy(false); return; }
    router.push("/participant/progress"); router.refresh();
  }
  if (completed) return <div className="success-summary"><h2>Today’s check-in is saved</h2><p>You can view progress or revise your plan. One day never defines the whole attempt.</p></div>;
  const triggers = [["stress", "Stress"], ["after-meals", "After meals"], ["alcohol", "Alcohol"], ["social", "Social situation"], ["boredom", "Boredom"], ["morning", "Morning routine"]];
  const coping = [["delay", "Delayed"], ["breathe", "Slow breathing"], ["water", "Had water"], ["walk", "Short walk"], ["message-support", "Messaged support"], ["change-routine", "Changed routine"], ["none", "None today"]];
  return <form className="long-form" onSubmit={submit}>{error && <div className="error-summary" role="alert"><p>{error}</p></div>}<section><h2>What happened today?</h2><label className="field"><span>Your own description of today</span><select name="smokingStatus" defaultValue="smoked"><option value="smoke_free">Smoke-free today</option><option value="smoked">Smoked today</option><option value="lapse">A lapse after being smoke-free</option><option value="returned_to_smoking">Returned to regular smoking</option><option value="prefer_not_to_say">Prefer not to say</option></select></label><div className="field-grid field-grid--two"><label className="field"><span>Number of cigarettes</span><input name="cigarettes" type="number" min="0" max="200" defaultValue="8" required /></label><label className="field"><span>Craving: 0 to 10</span><input name="craving" type="number" min="0" max="10" defaultValue="5" required /></label><label className="field"><span>Confidence: 0 to 10</span><input name="confidence" type="number" min="0" max="10" defaultValue="6" required /></label></div><fieldset className="question"><legend>Did you try the goal in your plan?</legend><label><input type="radio" name="goalAttempted" value="yes" defaultChecked />Yes</label><label><input type="radio" name="goalAttempted" value="no" />No</label></fieldset></section><section><h2>What was around the urge?</h2><div className="choice-grid">{triggers.map(([value, label]) => <label key={value}><input name="triggerCodes" value={value} type="checkbox" />{label}</label>)}</div></section><section><h2>What did you try?</h2><div className="choice-grid">{coping.map(([value, label]) => <label key={value}><input name="copingActionCodes" value={value} type="checkbox" />{label}</label>)}</div></section><section><h2>Notice one useful thing</h2><label className="field"><span>Choose the closest fit</span><select name="positiveMomentCode" defaultValue="checked-in"><option value="noticed-trigger">I noticed a trigger</option><option value="used-coping">I used a coping action</option><option value="asked-support">I asked for support</option><option value="smoked-less">I smoked less</option><option value="smoke-free">I was smoke-free</option><option value="checked-in">I checked in honestly</option><option value="none-yet">Nothing yet</option></select></label></section><div className="form-actions"><button className="button" disabled={busy}>{busy ? "Saving…" : "Save today’s check-in"}</button><p className="microcopy">A missing day remains unknown. A reported lapse is never changed into a failure label.</p></div></form>;
}
