"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

function csrfToken() { return decodeURIComponent(document.cookie.split("; ").find((part) => part.startsWith("mpft_csrf="))?.split("=").slice(1).join("=") ?? ""); }
export function FollowUpForm({ id, existing }: { id: string; existing: Record<string, unknown> }) {
  const router = useRouter(); const [status, setStatus] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(form: HTMLFormElement, action: "save" | "complete") { setBusy(true); const data = new FormData(form); const rawCigarettes = data.get("cigarettesPerDay"); const rawQuitAttempt = data.get("quitAttemptSinceBaseline"); const response = await fetch(`/api/participant/follow-ups/${id}`, { method: "POST", headers: { "content-type": "application/json", "x-csrf-token": csrfToken() }, body: JSON.stringify({ action, smokingStatus: data.get("smokingStatus") || null, cigarettesPerDay: rawCigarettes === "" || rawCigarettes === null ? null : Number(rawCigarettes), quitAttemptSinceBaseline: rawQuitAttempt === "yes" ? true : rawQuitAttempt === "no" ? false : null, supportUsed: data.getAll("supportUsed") }) }); const body = await response.json().catch(() => ({})); setBusy(false); setStatus(String(body.message ?? "The follow-up could not be saved.")); if (response.ok) router.refresh(); }
  const support = Array.isArray(existing.supportUsed) ? existing.supportUsed as string[] : [];
  return <form className="long-form" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); void submit(event.currentTarget, "complete"); }}><section><h2>Smoking since the follow-up window opened</h2><label htmlFor="smokingStatus">Smoking status</label><select id="smokingStatus" name="smokingStatus" defaultValue={String(existing.smokingStatus ?? "")}><option value="">Choose an answer</option><option value="not_smoked_past_7_days">I have not smoked in the past 7 days</option><option value="smoked_on_1_to_6_days">I smoked on 1 to 6 of the past 7 days</option><option value="smoked_daily">I smoked every day in the past 7 days</option><option value="prefer_not_to_answer">Prefer not to answer</option></select><label htmlFor="cigarettesPerDay">Cigarettes per day now <span>Optional</span></label><input id="cigarettesPerDay" name="cigarettesPerDay" type="number" min="0" max="200" defaultValue={existing.cigarettesPerDay == null ? "" : String(existing.cigarettesPerDay)} /></section><section><h2>Attempts and support</h2><fieldset className="question"><legend>Have you made a quit attempt since joining?</legend><label><input type="radio" name="quitAttemptSinceBaseline" value="yes" defaultChecked={existing.quitAttemptSinceBaseline === true} />Yes</label><label><input type="radio" name="quitAttemptSinceBaseline" value="no" defaultChecked={existing.quitAttemptSinceBaseline === false} />No</label><label><input type="radio" name="quitAttemptSinceBaseline" value="prefer" defaultChecked={existing.quitAttemptSinceBaseline == null} />Prefer not to answer</label></fieldset><fieldset className="question"><legend>Support used <span>Choose any that apply</span></legend><div className="check-list">{[["stop_smoking_service","Stop-smoking service"],["pharmacist_or_gp","Pharmacist or GP"],["telephone_support","Telephone support"],["digital_support","Digital support"],["friends_or_family","Friends or family"],["medicine_discussed_with_professional","Medicine discussed with a professional"],["none","None"],["prefer_not_to_answer","Prefer not to answer"]].map(([value,label]) => <label key={value}><input type="checkbox" name="supportUsed" value={value} defaultChecked={support.includes(value)} />{label}</label>)}</div></fieldset></section><div className="notice"><strong>Biochemical verification is separate.</strong> This form records self-report only. Current verification status is not requested; the app never converts self-report or silence into a verified outcome.</div><div className="form-actions"><button className="button" disabled={busy}>Complete follow-up</button><button className="button button--outline" type="button" disabled={busy} onClick={(event) => { if (event.currentTarget.form) void submit(event.currentTarget.form, "save"); }}>Save for later</button></div>{status && <div className="success-summary" role="status"><p>{status}</p></div>}</form>;
}
