import Link from "next/link";
import { requireServerSession } from "@/src/auth/server";
import { participantForUser } from "@/src/study/context";
import { progressWindow } from "@/src/study/check-ins";

const statusLabel: Record<string, string> = { smoke_free: "Smoke-free", smoked: "Smoked", lapse: "Participant-reported lapse", returned_to_smoking: "Participant-reported return to smoking", prefer_not_to_say: "Prefer not to say" };

export default async function ProgressPage() {
  const session = await requireServerSession(); const participant = await participantForUser(session.userId); const rows = participant ? await progressWindow(participant.id, 14) : [];
  const completed = rows.filter((row) => !row.missing); const cigaretteValues = completed.map((row) => row.cigarettes).filter((value): value is number => value !== null); const average = cigaretteValues.length ? cigaretteValues.reduce((a, b) => a + b, 0) / cigaretteValues.length : null;
  return <main id="main-content" className="app-content"><nav className="breadcrumbs"><Link href="/participant">Today</Link><span>/</span><span>Progress</span></nav><div className="app-title"><div><p className="eyebrow">Descriptive, not predictive</p><h1>Your recent records</h1><p>Missing days stay unknown. These summaries do not show that the programme caused a change.</p></div></div><div className="metric-grid"><article><span>Completed check-ins</span><strong>{completed.length}</strong><small>of {rows.length} scheduled days shown</small></article><article><span>Average cigarettes</span><strong>{average === null ? "Unknown" : average.toFixed(1)}</strong><small>completed days only</small></article><article><span>Smoke-free reports</span><strong>{completed.filter((row) => row.confirmedStatus === "smoke_free").length}</strong><small>participant-confirmed</small></article></div><section className="progress-card" aria-labelledby="recent-heading"><h2 id="recent-heading">Fourteen-day overview</h2><div className="progress-strip" role="img" aria-label={`${completed.length} of ${rows.length} scheduled check-ins completed. Missing days are shown as unknown.`}>{rows.map((row) => <span key={row.date} className={row.missing ? "progress-day progress-day--missing" : row.confirmedStatus === "smoke_free" ? "progress-day progress-day--free" : "progress-day progress-day--reported"} title={`${row.date}: ${row.missing ? "Unknown" : statusLabel[row.confirmedStatus ?? ""] ?? "Reported"}`}>{new Date(`${row.date}T12:00:00Z`).toLocaleDateString("en-GB", { weekday: "narrow" })}</span>)}</div><div className="table-scroll"><table><caption>Recorded and unknown days</caption><thead><tr><th scope="col">Date</th><th scope="col">Status</th><th scope="col">Cigarettes</th><th scope="col">Craving</th><th scope="col">Confidence</th></tr></thead><tbody>{rows.map((row) => <tr key={row.date}><th scope="row">{new Date(`${row.date}T12:00:00Z`).toLocaleDateString("en-GB", { day: "numeric", month: "short" })}</th><td>{row.missing ? "Unknown — no check-in" : statusLabel[row.confirmedStatus ?? ""] ?? "Reported"}</td><td>{row.missing ? "Unknown" : row.cigarettes ?? "Not answered"}</td><td>{row.missing ? "Unknown" : row.craving ?? "Not answered"}</td><td>{row.missing ? "Unknown" : row.confidence ?? "Not answered"}</td></tr>)}</tbody></table></div></section></main>;
}
