import Link from "next/link";
import { requireServerPermission } from "@/src/auth/server";
import { exportDictionary } from "@/src/research/export";
import { exportHistoryRows } from "@/src/research/staff-data";
import { ExportButtons } from "@/src/ui/staff/ExportButtons";

export default async function StaffExportsPage() {
  await requireServerPermission("exports:create"); const history = await exportHistoryRows();
  return <main id="main-content" className="app-content"><nav className="breadcrumbs"><Link href="/staff">Overview</Link><span>/</span><span>Exports and reports</span></nav><div className="app-title"><div><p className="eyebrow">Audited and analysis-ready</p><h1>Exports and reports</h1><p>Stable de-identified schemas with version, cutoff, denominator and missing-data metadata.</p></div></div><div className="notice"><strong>Contact identities and raw coach text are excluded.</strong> Raw-text export remains disabled; no raw coach text is stored in this configuration.</div><section className="staff-section"><h2>Generate export</h2><p>CSV repeats release metadata on each participant row. JSON includes a metadata block and generated field dictionary.</p><ExportButtons /></section><section className="staff-section"><h2>Data dictionary</h2><div className="table-scroll staff-table"><table><thead><tr><th>Field</th><th>Definition</th></tr></thead><tbody>{exportDictionary.map(([field, definition]) => <tr key={field}><td><code>{field}</code></td><td>{definition}</td></tr>)}</tbody></table></div></section><section className="staff-section"><h2>Immutable export history</h2>{history.length === 0 ? <p>No exports generated.</p> : <div className="table-scroll staff-table"><table><thead><tr><th>ID</th><th>Creator</th><th>Format/scope</th><th>Rows</th><th>Status</th><th>Generated</th><th>SHA-256</th></tr></thead><tbody>{history.map((run) => <tr key={run.id}><td><code>{run.id}</code></td><td>{run.creator}</td><td>{run.format}<br />{run.scope}</td><td>{run.rowCount ?? "—"}</td><td>{run.status}{run.includesRawText && <strong> raw text</strong>}</td><td>{run.completedAt?.toLocaleString("en-GB") ?? "Pending"}</td><td><code>{run.contentHash?.slice(0, 16) ?? "—"}…</code></td></tr>)}</tbody></table></div>}</section></main>;
}
